### PR TITLE
Update for 0.7-dev

### PR DESCRIPTION
**Pull request by dlfivefifty**

### CODE REVIEW

**Comment by MikaelSlevinsky** [comment]
Looks good to me. Does it still require Compat 0.17?

**Comment by MikaelSlevinsky** [comment]
this change is bad: I think the BLAS overrides are now allocating

**Comment by MikaelSlevinsky** [comment]
@dlfivefifty

**Comment by dlfivefifty** [comment]
Hmm, maybe we can only use ` Ref ` in 0.7 then?

**Comment by MikaelSlevinsky** [comment]
I think the tests show that it's allocating in 0.7 too. I don't think the performance is much worse, but still.

Probably a related issue in updating LowRankApprox.jl (and any other library using ccall)

Cheers,

Mikael

On Nov 5, 2017, at 7:33 PM, Sheehan Olver <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm, maybe we can only use Ref in 0.7 then?

**Comment by MikaelSlevinsky** [comment]
This is the lowered code from before and after.

Before, with no allocations:
```julia
julia> @code_lowered HierarchicalMatrices.A_mul_B!(y, A, x, 1, 1, 1, 1)
CodeInfo(:(begin 
        nothing
        SSAValue(0) = (Base.ptr_arg_cconvert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.UInt8), 'N')
        SSAValue(1) = (Base.ptr_arg_cconvert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.BlasInt), (HierarchicalMatrices.size)(A, 1))
        SSAValue(2) = (Base.ptr_arg_cconvert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.BlasInt), (HierarchicalMatrices.size)(A, 2))
        SSAValue(3) = (Base.ptr_arg_cconvert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.Float64), (HierarchicalMatrices.Float64)(1.0))
        SSAValue(4) = (Base.cconvert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.Float64), A)
        SSAValue(5) = (Base.ptr_arg_cconvert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.BlasInt), (HierarchicalMatrices.max)(1, (HierarchicalMatrices.stride)(A, 2)))
        SSAValue(6) = (Base.cconvert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.Float64), (HierarchicalMatrices.pointer)(x, jstart))
        SSAValue(7) = (Base.ptr_arg_cconvert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.BlasInt), INCX)
        SSAValue(8) = (Base.ptr_arg_cconvert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.Float64), (HierarchicalMatrices.Float64)(1.0))
        SSAValue(9) = (Base.cconvert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.Float64), (HierarchicalMatrices.pointer)(y, istart))
        SSAValue(10) = (Base.ptr_arg_cconvert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.BlasInt), INCY)
        $(Expr(:foreigncall, :((Core.tuple)(:dgemv_64_, HierarchicalMatrices.libblas)), Void, svec(Ptr{UInt8}, Ptr{Int64}, Ptr{Int64}, Ptr{Float64}, Ptr{Float64}, Ptr{Int64}, Ptr{Float64}, Ptr{Int64}, Ptr{Float64}, Ptr{Float64}, Ptr{Int64}), :(&((Base.ptr_arg_unsafe_convert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.UInt8), SSAValue(0)))), SSAValue(0), :(&((Base.ptr_arg_unsafe_convert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.BlasInt), SSAValue(1)))), SSAValue(1), :(&((Base.ptr_arg_unsafe_convert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.BlasInt), SSAValue(2)))), SSAValue(2), :(&((Base.ptr_arg_unsafe_convert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.Float64), SSAValue(3)))), SSAValue(3), :((Base.unsafe_convert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.Float64), SSAValue(4))), SSAValue(4), :(&((Base.ptr_arg_unsafe_convert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.BlasInt), SSAValue(5)))), SSAValue(5), :((Base.unsafe_convert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.Float64), SSAValue(6))), SSAValue(6), :(&((Base.ptr_arg_unsafe_convert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.BlasInt), SSAValue(7)))), SSAValue(7), :(&((Base.ptr_arg_unsafe_convert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.Float64), SSAValue(8)))), SSAValue(8), :((Base.unsafe_convert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.Float64), SSAValue(9))), SSAValue(9), :(&((Base.ptr_arg_unsafe_convert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.BlasInt), SSAValue(10)))), SSAValue(10))) # line 99:
        return y
    end))

```
After, with 8 allocations (on top of the original 4 due to time macro in the REPL):
```julia
julia> @code_lowered HierarchicalMatrices.A_mul_B!(y, A, x, 1, 1, 1, 1)
CodeInfo(:(begin 
        nothing
        SSAValue(0) = (Base.cconvert)((Core.apply_type)(HierarchicalMatrices.Ref, HierarchicalMatrices.UInt8), 'N')
        SSAValue(1) = (Base.cconvert)((Core.apply_type)(HierarchicalMatrices.Ref, HierarchicalMatrices.Int), (HierarchicalMatrices.size)(A, 1))
        SSAValue(2) = (Base.cconvert)((Core.apply_type)(HierarchicalMatrices.Ref, HierarchicalMatrices.Int), (HierarchicalMatrices.size)(A, 2))
        SSAValue(3) = (Base.cconvert)((Core.apply_type)(HierarchicalMatrices.Ref, HierarchicalMatrices.Float64), (HierarchicalMatrices.Float64)(1.0))
        SSAValue(4) = (Base.cconvert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.Float64), A)
        SSAValue(5) = (Base.cconvert)((Core.apply_type)(HierarchicalMatrices.Ref, HierarchicalMatrices.Int), (HierarchicalMatrices.max)(1, (HierarchicalMatrices.stride)(A, 2)))
        SSAValue(6) = (Base.cconvert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.Float64), (HierarchicalMatrices.pointer)(x, jstart))
        SSAValue(7) = (Base.cconvert)((Core.apply_type)(HierarchicalMatrices.Ref, HierarchicalMatrices.Int), INCX)
        SSAValue(8) = (Base.cconvert)((Core.apply_type)(HierarchicalMatrices.Ref, HierarchicalMatrices.Float64), (HierarchicalMatrices.Float64)(1.0))
        SSAValue(9) = (Base.cconvert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.Float64), (HierarchicalMatrices.pointer)(y, istart))
        SSAValue(10) = (Base.cconvert)((Core.apply_type)(HierarchicalMatrices.Ref, HierarchicalMatrices.Int), INCY)
        $(Expr(:foreigncall, :((Core.tuple)(:dgemv_64_, HierarchicalMatrices.libblas)), Void, svec(Ref{UInt8}, Ref{Int64}, Ref{Int64}, Ref{Float64}, Ptr{Float64}, Ref{Int64}, Ptr{Float64}, Ref{Int64}, Ref{Float64}, Ptr{Float64}, Ref{Int64}), :((Base.unsafe_convert)((Core.apply_type)(HierarchicalMatrices.Ref, HierarchicalMatrices.UInt8), SSAValue(0))), SSAValue(0), :((Base.unsafe_convert)((Core.apply_type)(HierarchicalMatrices.Ref, HierarchicalMatrices.Int), SSAValue(1))), SSAValue(1), :((Base.unsafe_convert)((Core.apply_type)(HierarchicalMatrices.Ref, HierarchicalMatrices.Int), SSAValue(2))), SSAValue(2), :((Base.unsafe_convert)((Core.apply_type)(HierarchicalMatrices.Ref, HierarchicalMatrices.Float64), SSAValue(3))), SSAValue(3), :((Base.unsafe_convert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.Float64), SSAValue(4))), SSAValue(4), :((Base.unsafe_convert)((Core.apply_type)(HierarchicalMatrices.Ref, HierarchicalMatrices.Int), SSAValue(5))), SSAValue(5), :((Base.unsafe_convert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.Float64), SSAValue(6))), SSAValue(6), :((Base.unsafe_convert)((Core.apply_type)(HierarchicalMatrices.Ref, HierarchicalMatrices.Int), SSAValue(7))), SSAValue(7), :((Base.unsafe_convert)((Core.apply_type)(HierarchicalMatrices.Ref, HierarchicalMatrices.Float64), SSAValue(8))), SSAValue(8), :((Base.unsafe_convert)((Core.apply_type)(HierarchicalMatrices.Ptr, HierarchicalMatrices.Float64), SSAValue(9))), SSAValue(9), :((Base.unsafe_convert)((Core.apply_type)(HierarchicalMatrices.Ref, HierarchicalMatrices.Int), SSAValue(10))), SSAValue(10))) # line 99:
        return y
    end))

```

**Comment by dlfivefifty** [comment]
I don't see the allocations in 0.7 with the following test example:
```julia
import Base.BLAS: libblas, BlasInt

A = randn(3, 10); x = randn(10); y = randn(10);

function amp_gbmv!(trans::Char, m::Int, n::Int, kl::Int, ku::Int, alpha::(Float64),
                             A::Ptr{Float64}, st::Int,
                             x::Ptr{Float64}, incx::Int, beta::(Float64), y::Ptr{Float64}, incy::Int)
	  ccall((:dgbmv_64_, libblas), Void,
		  (Ptr{UInt8}, Ptr{BlasInt}, Ptr{BlasInt}, Ptr{BlasInt},
		   Ptr{BlasInt}, Ptr{Float64}, Ptr{Float64}, Ptr{BlasInt},
		   Ptr{Float64}, Ptr{BlasInt}, Ptr{Float64}, Ptr{Float64},
		   Ptr{BlasInt}),
		   &trans, &m, &n, &kl,
		   &ku, &alpha, A, &st,
		   x, &incx, &beta, y, &incy)
	  y
end

function ref_gbmv!(trans::Char, m::Int, n::Int, kl::Int, ku::Int, alpha::(Float64),
                             A::Ptr{Float64}, st::Int,
                             x::Ptr{Float64}, incx::Int, beta::(Float64), y::Ptr{Float64}, incy::Int)
       
  ccall((:dgbmv_64_, libblas), Void,
	  (Ref{UInt8}, Ref{BlasInt}, Ref{BlasInt}, Ref{BlasInt},
	   Ref{BlasInt}, Ref{Float64}, Ptr{Float64}, Ref{BlasInt},
	   Ptr{Float64}, Ref{BlasInt}, Ref{Float64}, Ptr{Float64},
	   Ref{BlasInt}),
	   trans, m, n, kl,
	   ku, alpha, A, st,
	   x, incx, beta, y, incy)
  y
end

@time amp_gbmv!('N', 10, 10, 1, 1, 0.1, pointer(A), 3, pointer(x), 1, 1.0,pointer(y),1);
@time amp_gbmv!('N', 10, 10, 1, 1, 0.1, pointer(A), 3, pointer(x), 1, 1.0,pointer(y),1);

@time ref_gbmv!('N', 10, 10, 1, 1, 0.1, pointer(A), 3, pointer(x), 1, 1.0,pointer(y),1);
@time ref_gbmv!('N', 10, 10, 1, 1, 0.1, pointer(A), 3, pointer(x), 1, 1.0,pointer(y),1);
```

so I think we just need an `if __VERSION__ > v"0.6"` test to include the old version.

I'll prepare a fix.

**Comment by dlfivefifty** [comment]
i.e., with your example:

```julia
julia> @time HierarchicalMatrices.A_mul_B!(y, A, x, 1, 1, 1, 1)
  0.000007 seconds (4 allocations: 160 bytes)
10-element Array{Float64,1}:
   5.718894765660483 
  12.19531230761731  
 -13.017541031074563 
   1.6607409794382124
  -2.3285088836731274
   0.3019603634797574
  -0.5285614989055852
   1.3526272971091853
   0.7272495481079007
  -1.4144749676837802

julia> versioninfo()
Julia Version 0.7.0-DEV.2425
Commit 33763a01c3 (2017-11-03 21:33 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin17.2.0)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)
Environment:
  JULIA_VERSION = 0.6
```

**Comment by dlfivefifty** [comment]
I just pushed a fix

**Comment by MikaelSlevinsky** [comment]
somehow you're on 0.7.0-DEV.2425, but the nightlies are 0.7.0-DEV.2158 (linux) and 0.7.0-DEV.2098 (os x and windows)

the change to julia itself occurred here:

https://github.com/JuliaLang/julia/commit/e56400841abafefe3db7a16a55a7fed3e4ec2e31

how do we reference that as a version?

**Comment by dlfivefifty** [comment]
I build from source.

I never figured out how to work out which dev number from a commit number, but I'm not too worried about being precise since the code still works on older devs.

**Comment by MikaelSlevinsky** [comment]
That's ok. Thanks!

**Pull request merged**
